completed the task UiStretch
js-tasks-ru/vue-20240627_admin6 pull request #11
Opened 2024-10-07 07:22 UTC by alexmenshikov

Правильное ли такое решение?

2024-10-07 07:22 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-07 17:51 UTC, ShGKme requested changes

2024-10-07 17:51 UTC, ShGKme commented on 04-sfc/30-UiStretch/UiStretch.vue
> +:deep(.stretch-container > picture) {
Такое решение работает. Но, если в содержимое компонента даже где-то глубоко-глубоко случайно тоже будет элемент попадающий под `.stretch-container > img` - на него эти стили тоже подействуют.

Нужно немного поправить селектор так, чтобы он действовал только и только на `img/video` являющиеся непосредственно дочерними для дива этого компонента.

2024-10-09 14:26 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-09 14:27 UTC, alexmenshikov commented
Если :deep применить только к самим img/video, а не полностью всё оборачивать

2024-10-13 22:32 UTC, ShGKme approved these changes

2024-10-13 22:32 UTC, ShGKme commented on 04-sfc/30-UiStretch/UiStretch.vue
> +.stretch-container > :deep(picture) {
Хотя `deep` с `>` работает точно также, лучше здесь использовать `:slotted`. Семантически - стилизуется именно содержимое слота.

2024-10-13 22:33 UTC, merged